### ISSUE TITLE
Omnicompletion not working on Windows with vim 7.3 and Ruby 1.9.2

### ISSUE THREAD

**Issue by duckpuppy** [vim-ruby/vim-ruby#47]
Attempting to use omnicompletion in Windows vim 7.3 in a ruby (.rb) file gives the following error:
NoMethodError: undefined method `line_number' for 15:Fixnum

If I try `execute "ruby puts VIM::Buffer.current.line_number"` as an ex command I can replicate the error. `execute "ruby puts VIM::Buffer.current"` returns 15.
